ignore:
  - "app/src/main/java/com/rickyhu/hushkeyboard/*.kt"
  - "app/src/main/java/com/rickyhu/hushkeyboard/data/*.kt"
  - "app/src/main/java/com/rickyhu/hushkeyboard/service/*.kt"
  - "app/src/main/java/com/rickyhu/hushkeyboard/utils/*.kt"
